tabs
theseanl/deob pull request #1
Opened 2017-02-16 15:25 UTC by seanl-adg

Add 'tabs' ability at the main editor at the left side of the page.
Each tabs contain an ace editor in it. Tabs can be created by clicking on the + button, closed by clicking on x button at its title. Tabs' title can be changed by double-clicking on the title area. Contents of tabs are automatically saved and restored when a user visits the page with the same browser.

2017-02-26 20:05 UTC, ameshkov requested changes

2017-02-26 20:05 UTC, ameshkov commented on deobfuscator/comm.js
> +        function evalScript(evt){
Just in case, it'd be better to introduce some kind of a message format, so that you could distinguish your messages.

```
{
    requestId: 123,
    type: "sandboxEval",
    script: "script code goes here"
}
```

2017-02-26 20:05 UTC, ameshkov commented on deobfuscator/comm.js
> +                parent.postMessage({"success": 1, "result":_eval(evt.data)}, "%ORIGIN%");
When posting result, you'd better reuse the `requestId` from the suggested message format.

2017-02-26 20:05 UTC, ameshkov commented on deobfuscator/comm.js
> + * Usage: var seval = new SandboxEval(window.location.href);
You should use it in an async manner:
```
var safeEval = new SandboxEval();
// eval returns a Promise object
safeEval.eval(code).then(function(result) {
    console.log('eval result is ' + result);
}).catch(function(reason) {
    console.log('Cannot eval due to ' + reason);
}
```

2017-04-04 02:20 UTC, merged

2017-04-04 02:21 UTC, seanl-adg commented
will refine eval part later